name: Notify on Star

on:
  watch:
    types: [started]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Send email
      run: |
        echo "Someone starred your repository on GitHub." | mail -s "Repository Starred" ${{ secrets.EMAIL_NOTIFICATION }}
      env:
        EMAIL_NOTIFICATION: ${{ secrets.EMAIL_NOTIFICATION }}
